/*
# Create stock analysis tables

## Purpose
Stores Vietnamese stock technical analyses generated by the 6-step analysis pipeline.
This is a single-tenant app (no sign-in), so data is shared/public across all visitors.

## New Tables

### stock_analyses
- `id` (uuid, primary key)
- `ticker` (text, not null) — stock ticker symbol, e.g. "VNM", "FPT"
- `current_price` (numeric) — latest closing price
- `change_pct` (numeric) — percentage change vs previous close
- `ma20` (numeric) — 20-period moving average
- `ma50` (numeric) — 50-period moving average
- `xu_huong_ngan` (text) — short-term trend label
- `xu_huong_trung` (text) — medium-term trend label
- `resistances` (numeric array) — resistance price levels
- `supports` (numeric array) — support price levels
- `rsi` (numeric) — RSI(14) value
- `rsi_label` (text) — RSI zone label
- `bb_upper` (numeric) — Bollinger upper band
- `bb_basis` (numeric) — Bollinger middle band
- `bb_lower` (numeric) — Bollinger lower band
- `vol_label` (text) — volume status label
- `vol_ratio` (numeric) — volume ratio vs 20-period average
- `analysis` (jsonb) — full structured analysis output (the JSON from the pipeline)
- `created_at` (timestamptz, default now())

### watchlist
- `id` (uuid, primary key)
- `ticker` (text, not null) — stock ticker symbol
- `note` (text) — optional user note
- `created_at` (timestamptz, default now())

## Security
- RLS enabled on both tables.
- Both tables are intentionally public/shared (single-tenant, no auth).
- CRUD allowed for anon + authenticated roles.
*/

CREATE TABLE IF NOT EXISTS stock_analyses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticker text NOT NULL,
  current_price numeric NOT NULL,
  change_pct numeric NOT NULL DEFAULT 0,
  ma20 numeric,
  ma50 numeric,
  xu_huong_ngan text,
  xu_huong_trung text,
  resistances numeric[] DEFAULT '{}',
  supports numeric[] DEFAULT '{}',
  rsi numeric,
  rsi_label text,
  bb_upper numeric,
  bb_basis numeric,
  bb_lower numeric,
  vol_label text,
  vol_ratio numeric,
  analysis jsonb,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_stock_analyses_ticker ON stock_analyses(ticker);
CREATE INDEX IF NOT EXISTS idx_stock_analyses_created_at ON stock_analyses(created_at DESC);

ALTER TABLE stock_analyses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_stock_analyses" ON stock_analyses;
CREATE POLICY "anon_select_stock_analyses" ON stock_analyses FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_stock_analyses" ON stock_analyses;
CREATE POLICY "anon_insert_stock_analyses" ON stock_analyses FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_stock_analyses" ON stock_analyses;
CREATE POLICY "anon_update_stock_analyses" ON stock_analyses FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_stock_analyses" ON stock_analyses;
CREATE POLICY "anon_delete_stock_analyses" ON stock_analyses FOR DELETE
  TO anon, authenticated USING (true);

CREATE TABLE IF NOT EXISTS watchlist (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticker text NOT NULL,
  note text,
  created_at timestamptz DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_watchlist_ticker ON watchlist(ticker);

ALTER TABLE watchlist ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_watchlist" ON watchlist;
CREATE POLICY "anon_select_watchlist" ON watchlist FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_watchlist" ON watchlist;
CREATE POLICY "anon_insert_watchlist" ON watchlist FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_watchlist" ON watchlist;
CREATE POLICY "anon_delete_watchlist" ON watchlist FOR DELETE
  TO anon, authenticated USING (true);
